- hosts: target
  remote_user: vagrant
  become: true
  tasks:
    
    - name: install required dependencies 
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    
    - name: add GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    
    - name: add docker repository to apt
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    
    - name: install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    
    - name: start docker service
      service:
        name: docker
        state: started
        enabled: yes
    
    - name: Ensure group docker exists
      ansible.builtin.group:
        name: docker
        state: present
    
    - name: adding vagrant to docker group
      user:
        name: vagrant
        groups: docker
        append: yes
    
    - name: Pull a Docker image from registry 
      community.docker.docker_image:
        name: ahmedelenany703/weather-app
        source: pull

    - name: Run the Docker container
      community.docker.docker_container:
        name: weather-app
        image: ahmedelenany703/weather-app
        state: started
        detach: yes
        ports:
          - "5000:5000"
